export const SET_COORDINATES_BOARD = "@SETCOORDINATES/BOARD";
export const SET_COORDINATES_BLANKCELL = "@SETCOORDINATES/BLANKCELL";
export const CELLS_SHUFFLE = "@CELLS/SHUFFLE";
export const CELLS_REORDER = "@CELLS/REORDER";
