export const SHUFFLE_CELLS = "SHUFFLE_CELLS";
export const SET_BLANK_CELL_COORDINATES = "SET_BLANK_CELL_COORDINATES";
export const SET_BOARD_COORDINATES = "SET_BOARD_COORDINATES";
export const REORDER_CELLS = "REORDER_CELLS";
export const CHECK_FOR_WIN = "CHECK_FOR_WIN";
export const INCREMENT_MOVES = "INCREMENT_MOVES";
